data_params:
  pkl_path: 'data2/deepcad_solid_deduplicated_id.pkl'
  max_bbox_num: 40
  data_size: -1

network_params:
  input_channel: 6
  d_model: 768
  nhead: 12
  dim_feedforward: 1024
  dropout: 0.1

trainer_params:
  batch_size: 256
  lr: 0.0001
  weight_decay: 0.0
  lr_decay: 0.99
  accelerator: 'gpu'
  max_epochs: 3000
  devices: 1
  strategy: 'ddp'
  log_every_n_steps: 100
  gradient_clip_val: 1.0
  default_root_dir: 'bbox/logs/full'



